---
image:
  name: python

stages:
  - test

lint:
  stage: test
  only:
    refs:
      - master
      - web
  script:
    - "pip install --no-cache-dir 'ansible-lint<4.3' yamllint"
    - 'ansible-lint -v .'
    - 'yamllint -c .yamllint.yml .'
...
