---
- name: Set internal variable platform-suffix for convenience
  ansible.builtin.set_fact:
    prometheus_platform_suffix: "linux-amd64"
  when: ansible_architecture == "x86_64"

- name: Set internal variable platform-suffix for convenience
  ansible.builtin.set_fact:
    prometheus_platform_suffix: "linux-armv7"
  when: ansible_architecture == "armv7l"

- name: Set internal variable platform-suffix for convenience
  ansible.builtin.set_fact:
    prometheus_platform_suffix: "linux-arm64"
  when: ansible_architecture == "aarch64"

- name: Set internal variables for convenience
  ansible.builtin.set_fact:
    prometheus_node_exporter_subdir: "{{ prometheus_node_exporter_install_path }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_suffix }}"  # noqa 204

- name: Set internal variables for convenience
  ansible.builtin.set_fact:
    prometheus_node_exporter_daemon_dir: "{{ prometheus_node_exporter_subdir }}"

- name: Set download url for versions
  ansible.builtin.set_fact:
    prometheus_node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"  # noqa 204

- name: Create Prometheus group
  ansible.builtin.group:
    name: '{{ prometheus_node_exporter_group }}'
    state: present

- name: Create Prometheus user
  ansible.builtin.user:
    name: "{{ prometheus_node_exporter_user }}"
    group: "{{ prometheus_node_exporter_group }}"
    createhome: false
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present

- name: MkDir for prometheus and node_exporter
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_node_exporter_user }}"
    group: "{{ prometheus_node_exporter_group }}"
    mode: '0750'
  loop:
    - "{{ prometheus_node_exporter_install_path }}"
    - "{{ prometheus_node_exporter_config_path }}"

- name: Download and untar node_exporter tarball
  ansible.builtin.unarchive:
    src: "{{ prometheus_node_exporter_tarball_url }}"
    dest: "{{ prometheus_node_exporter_install_path }}"
    owner: '{{ prometheus_node_exporter_user }}'
    group: '{{ prometheus_node_exporter_group }}'
    copy: false
    creates: '{{ prometheus_node_exporter_subdir }}'
    validate_certs: '{{ prometheus_node_exporter_validate_certs }}'
  notify:
    - restart node_exporter

- name: Copy node_exporter systemd profile
  ansible.builtin.template:
    src: 'node_exporter.service.j2'
    dest: '/lib/systemd/system/node_exporter.service'
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemd reload
    - restart node_exporter
  when: ansible_service_mgr == "systemd"

- name: Copy node_exporter sysvinit profile
  ansible.builtin.template:
    src: 'node_exporter.initd.j2'
    dest: '/etc/init.d/node_exporter'
    owner: root
    group: root
    mode: '0755'
  notify:
    - restart node_exporter
  when: ansible_service_mgr == "sysvinit"

- name: Copy node_exporter config
  ansible.builtin.template:
    src: 'node_exporter.defaults.j2'
    dest: '/etc/default/node_exporter'
    owner: '{{ prometheus_node_exporter_user }}'
    group: '{{ prometheus_node_exporter_group }}'
    mode: '0640'
  notify:
    - restart node_exporter

- name: Node_exporter service enable
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true

...
