---

- name: install prometheus node_exporter
  include: install.yaml
  tags:
    - prometheus
    - node_exporter

- name: ufw | open access to node_exporter
  include: ufw.yaml
  when: enable_ufw | bool
  tags:
    - prometheus
    - node_exporter
    - ufw
