---
- name: Restart node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: restarted
  tags:
    - prometheus
    - node_exporter

- name: Systemd reload
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - prometheus
    - node_exporter
...
